use_amp: True
use_ema: True
ema:
  type: ModelEMA
  decay: 0.9999
  warmups: 1000
  start: 0


epochs: 72
clip_max_norm: 0.1


optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm).*$'
      lr: 0.0001
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.001
  betas: [0.9, 0.999]
  weight_decay: 0.000125

grad_max_norm: 0.1

# lr_scheduler:
#   type: MultiStepLR
#   milestones: [500]
#   gamma: 0.1

# 만약 D-FINE 툴킷 스케줄러 지정 방식이 클래스 타입 지정 형태라면 아래와 같이 변경합니다.
lr_scheduler:
  type: MultiStepLR
  milestones: [3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72]
  gamma: 0.7 

lr_warmup_scheduler:
  type: LinearWarmup
  warmup_duration: 125  # 1000