use_amp: True
use_ema: True
ema:
  type: ModelEMA
  decay: 0.9999
  warmups: 1000
  start: 0

epochs: 72
clip_max_norm: 0.1
grad_max_norm: 0.1 # LR 폭발 방지

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm).*$'
      # lr: 0.000003
      lr: 0.00001
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.0001
  # lr: 0.00003
  betas: [0.9, 0.999]
  weight_decay: 0.000125


lr_scheduler:
  type: MultiStepLR
  milestones: [36, 54, 60]
  gamma: 0.3

lr_warmup_scheduler:
  type: LinearWarmup
  # 웜업 지속 기간을 1000으로 늘려줍니다. (가상 배치 8배이므로 화면상으론 8,000스텝)
  # 이렇게 하면 약 1.8에포크 동안 아주 천천히 예열되면서 0.0001에 도달하므로 절대 튀지 않습니다.
  warmup_duration: 1000